Project2/force-app/main/default/objects/Questions__c/fields/A__c.field-meta.xml
<CustomField>
    <fullName>A__c</fullName>
    <label>A</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project2/force-app/main/default/objects/Questions__c/fields/B__c.field-meta.xml
<CustomField>
    <fullName>B__c</fullName>
    <label>B</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Project2/force-app/main/default/objects/Questions__c/fields/CorrectAnswer__c.field-meta.xml
<CustomField>
    <fullName>CorrectAnswer__c</fullName>
    <label>CorrectAnswer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project2/force-app/main/default/classes/QuizPageControllerTest.cls
@isTest
public class QuizPageControllerTest {
    
@testSetup
public static void datafactory(){
    account acc = new account(name='test');
    insert acc;
    
    quiz__c nc=new quiz__c(name='j');
    insert nc;
    
    list<quiz__c> qz2=[SELECT id FROM quiz__c];
    questions__c qs= new questions__c(name='jj', quiz__c=qz2[0].id, a__c='a',
                                     b__c='b',c__c='c',d__c='d',CorrectAnswer__c='c');
    insert qs;
    
    questions__c qs2= new questions__c(name='jjj', quiz__c=qz2[0].id, a__c='a',
                                     b__c='b',c__c='c',d__c='d',CorrectAnswer__c='c');
    insert qs2;
}
    
    
@isTest
    public static void Test1(){
    QuizPageController qz = new QuizPageController();
        System.assertNotEquals(null, qz.q);
        System.assertNotEquals(null, qz.ques);
        System.debug(qz.ques);
        
        quiz__c result1=qz.getQuiz();
        questions__c result2 = qz.getQuestions();
        list<selectoption> result3 = qz.getAnswers();
        System.assertNotEquals(null, result1);
        System.assertNotEquals(null, result2);
        System.assertNotEquals(null, result3);
        
        
        System.assertEquals(False, qz.getNxt());
        System.assertEquals(True, qz.getLst());
        qz.next();
        System.assertEquals(1, qz.count);
        //System.assertEquals(1,qz.score);
        qz.getNxt();
        qz.getLst();
        //count=1
        
        qz.submit();
        list<accountQuiz__c> result4=[SELECT name FROM AccountQuiz__c];
        System.assertNotEquals(null, result4);
    }
    
    
    
}