Project2/force-app/main/default/objects/Account/fields/AccountUser__c.field-meta.xml
<CustomField>
    <fullName>AccountUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

Project2/force-app/main/default/objects/Account/fields/AvgScore__c.field-meta.xml
<CustomField>
    <fullName>AvgScore__c</fullName>
    <formula>IF(NumQuizzes__c!=0, TotalScore__c /  NumQuizzes__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Avg Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Project2/force-app/main/default/classes/Team.cls
public with sharing class Team {
    //Overall Score of the team
    public double score;

    //Team
    public CollaborationGroup Chattergroup;

    //List of team members
    public List<Account> members;

    public Team(collaborationGroup passedGroup) {

        Chattergroup = passedGroup;
        score = 0;

        //get the id of the users in the chatter group
        List<CollaborationGroupMember> teamMemberUsers = [SELECT id, MemberId FROM CollaborationGroupMember WHERE CollaborationGroupid= :Chattergroup.id];
        
        //for each user, find their account, and add to the list of team members
        for(CollaborationGroupMember cgm: teamMemberUsers)
        {
            Account foundHim = [SELECT id, name, AvgScore__c FROM Account WHERE AccountUser__c = :cgm.id];
            score = score + foundHim.AvgScore__c;
            members.add(foundHim);
        }

        //determine overall score based on score of the individual users
        score = score/members.size();
        
        

    }
}