Project2/force-app/main/default/objects/Account/fields/AvgScore__c.field-meta.xml
<CustomField>
    <fullName>AvgScore__c</fullName>
    <formula>IF(NumQuizzes__c!=0, TotalScore__c /  NumQuizzes__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Avg Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Project2/force-app/main/default/objects/Account/fields/NumQuizzes__c.field-meta.xml
<CustomField>
    <fullName>NumQuizzes__c</fullName>
    <label>Number of Quizzes</label>
    <summaryForeignKey>AccountQuiz__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Project2/force-app/main/default/objects/Account/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <label>Ranking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project2/force-app/main/default/objects/Account/fields/TotalScore__c.field-meta.xml
<CustomField>
    <fullName>TotalScore__c</fullName>
    <label>Total Score</label>
    <summarizedField>AccountQuiz__c.Score__c</summarizedField>
    <summaryForeignKey>AccountQuiz__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Project2/force-app/main/default/classes/playerDetailTest.cls
@isTest
public class playerDetailTest {
    @testSetup static void Setup(){
        Account playerAccount = new Account(name='Player', ranking__c=100);
        insert playerAccount;
    }
    
    @isTest static void testPlayerDetailComponent(){
        AccountController acctCont = new AccountController();
        acctCont.acct = new Account();
        Account act = [SELECT id, name, NumQuizzes__c, AvgScore__c, TotalScore__c, Ranking__c FROM Account LIMIT 1];
        System.assertEquals(acctCont.getActiveAccount(), act);
    }
}